on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 2 * * *' # Run everyday, at 2AM UTC.
name: ci-profiler
jobs:
  system-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm run system-test
      - name: coverage
        uses: codecov/codecov-action@v1
        with:
          name: actions system-test
          fail_ci_if_error: false
  golint:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - run: gofmtdiff=$(gofmt -s -d .) && if [ -n "$gofmtdiff" ]; then printf 'gofmt -s found:\n%s\n' "$gofmtdiff" && exit 1; fi
      - run: go get -u golang.org/x/lint/golint && golintlint=$($GOPATH/bin/golint ./...) && if [ -n "$golintlint" ]; then printf 'golint found:\n%s\n' "$golintlint" && exit 1; fi
